name: CI

on:
  push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Basic check
        run: |
          echo "CI workflow triggered successfully"
          ls -R
